/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Account;
import Model.TaiKhoan;
import view.*;

import service.TaiKhoanService;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class DANHMUCTAIKHOANView extends javax.swing.JFrame {
	TaiKhoanService taiKhoanService = new TaiKhoanService();
	DefaultTableModel defaultTableModel;

	/**
	 * Creates new form DANHMUCTAIKHOANView
	 */
	public DANHMUCTAIKHOANView() {
		initComponents();
		loadData();

	}

	private void loadData() {
		defaultTableModel = new DefaultTableModel();
		tableAccout.setDefaultEditor(Object.class, null);
		defaultTableModel.addColumn("Tên đăng nhập");
		defaultTableModel.addColumn("Mật khẩu");
		defaultTableModel.addColumn("Quyền");
		List<TaiKhoan> data = taiKhoanService.findAll();
		for (TaiKhoan tk : data) {
			Vector<Object> row = new Vector<Object>();
			row.add(tk.getTenDangNhap());
			row.add(tk.getMatKhau());
			row.add(tk.getQuyen());
			defaultTableModel.addRow(row);
		}
		tableAccout.setModel(defaultTableModel);
		tableAccout.setAutoCreateRowSorter(true);
		tableAccout.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				int index = tableAccout.getSelectedRow();
				displayDetails(index);

			}
		});
		tableAccout.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				if (e.getKeyCode() == KeyEvent.VK_UP || e.getKeyCode() == KeyEvent.VK_DOWN) {
					int index = tableAccout.getSelectedRow();
					displayDetails(index);
				}
			}
		});
	}

	private void displayDetails(int index) {
		String tendangnhap = (String) defaultTableModel.getValueAt(index, 0);
		TaiKhoan tk = taiKhoanService.findByUsername(tendangnhap);
		fieldUserName.setText(tk.getTenDangNhap());
		fieldPassword.setText(tk.getMatKhau());
		fieldAccessRight.setText(tk.getQuyen());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		tableAccout = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		fieldUserName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		fieldPassword = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		fieldAccessRight = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		addBtn = new javax.swing.JButton();
		updateBtn = new javax.swing.JButton();
		deleteBtn = new javax.swing.JButton();
		backBtn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		tableAccout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		tableAccout
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null }, { null, null, null }, { null, null, null },
								{ null, null, null } },
						new String[] { "Tên đăng nhập", "Mật khẩu", "Quyền truy cập" }));
		jScrollPane1.setViewportView(tableAccout);

		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		jLabel2.setText("Tên đăng nhập:");

		fieldUserName.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

		jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		jLabel3.setText("Mật khẩu:");

		fieldPassword.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

		jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		jLabel4.setText("Quyền truy cập");

		fieldAccessRight.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel3)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel4).addGap(18, 18, 18)
										.addComponent(fieldAccessRight, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4).addComponent(fieldAccessRight,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
		jLabel1.setText("Cập Nhật Tài Khoản");

		addBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		addBtn.setText("Thêm tài khoản");
		addBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addBtnActionPerformed(evt);
			}
		});

		updateBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		updateBtn.setText("Cập nhật quyền ");
		updateBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateBtnActionPerformed(evt);
			}
		});

		deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		deleteBtn.setText("Xóa tài khoản");
		deleteBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteBtnActionPerformed(evt);
			}
		});

		backBtn.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
		backBtn.setText("Trở về");
		backBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backBtnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(245, 245, 245).addComponent(jLabel1).addGap(0,
								0, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(updateBtn).addComponent(jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE, 340,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(addBtn))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addComponent(deleteBtn)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(backBtn))
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addGap(26, 26, 26).addComponent(jLabel1).addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(addBtn).addComponent(updateBtn).addComponent(deleteBtn)
								.addComponent(backBtn))
						.addContainerGap(22, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addBtnActionPerformed
		String tenDangNhap = fieldUserName.getText();
		String matKhau = fieldPassword.getText();
		String quyen = fieldAccessRight.getText();
		TaiKhoan tk = new TaiKhoan();
		if (!tenDangNhap.equals("") && !matKhau.equals("") && !quyen.equals(""))
		tk.setTenDangNhap(tenDangNhap);
		tk.setMatKhau(matKhau);
		tk.setQuyen(quyen);
		if (taiKhoanService.findByUsername(tenDangNhap) != null)
			JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại");
		else if (taiKhoanService.add(tk) && checkRight(quyen) == true) {
			JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công");
			loadData();
			resetField();
		
		} else
			JOptionPane.showMessageDialog(this, "Thêm tài khoản không thành công");

	}// GEN-LAST:event_addBtnActionPerformed

	private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateBtnActionPerformed
		int selectedIndex = tableAccout.getSelectedRow();
		if (selectedIndex == -1) {
			JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản muốn cập nhật");
		} else {
			String tenDangNhap = (String) defaultTableModel.getValueAt(selectedIndex, 0);
			String quyen = (String) defaultTableModel.getValueAt(selectedIndex, 2);
			TaiKhoan t = taiKhoanService.findByUsername(tenDangNhap);
			t.setTenDangNhap(fieldUserName.getText());
			t.setMatKhau(fieldPassword.getText());
			t.setQuyen(fieldAccessRight.getText());
			if (checkRight(quyen) == true) {
				taiKhoanService.update(t);
				JOptionPane.showMessageDialog(this, "Cập nhật thành công");
				loadData();
				resetField();
			} else if (checkRight(quyen) == false) {
				JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra lại quyền");
			} else
				JOptionPane.showMessageDialog(this, "Cập nhật không thành công");

		}
	}// GEN-LAST:event_updateBtnActionPerformed

	private boolean checkRight(String right) {
		right = fieldAccessRight.getText();
		if (right.equals("ketoan") || right.equals("nhansu") || right.equals("admin")) {
			return true;
		}
		return false;
	}

	private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBtnActionPerformed
		int selectedIndex = tableAccout.getSelectedRow();
		if (selectedIndex == -1) {
			JOptionPane.showMessageDialog(this, "Vui lòng chọn tài khoản muốn xóa");
		} else {
			String tenDangNhap = (String) defaultTableModel.getValueAt(selectedIndex, 0);
			TaiKhoan t = taiKhoanService.findByUsername(tenDangNhap);
			if (JOptionPane.showConfirmDialog(this, "Bạn thật sự muốn xóa tài khoản này?", "Thông báo",
					JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
				if (taiKhoanService.delete(t)) {
					JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công");
					loadData();
					resetField();
				} else
					JOptionPane.showMessageDialog(this, "Xóa tài khoản không thành công");
			}
		}
	}// GEN-LAST:event_deleteBtnActionPerformed

	private void resetField() {
		fieldUserName.setText(null);
		fieldPassword.setText(null);
		fieldAccessRight.setText(null);
	}

	private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnActionPerformed
		HETHONGView heThongView = new HETHONGView();
		heThongView.setVisible(true);
		heThongView.setLocationRelativeTo(null);
		heThongView.setResizable(false);
		this.dispose();
	}// GEN-LAST:event_backBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DANHMUCTAIKHOANView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DANHMUCTAIKHOANView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DANHMUCTAIKHOANView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DANHMUCTAIKHOANView.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DANHMUCTAIKHOANView danhMucTaiKhoanView = new DANHMUCTAIKHOANView();
				danhMucTaiKhoanView.setVisible(true);
				danhMucTaiKhoanView.setLocationRelativeTo(null);
				danhMucTaiKhoanView.setResizable(false);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addBtn;
	private javax.swing.JButton backBtn;
	private javax.swing.JButton deleteBtn;
	private javax.swing.JTextField fieldAccessRight;
	private javax.swing.JTextField fieldPassword;
	private javax.swing.JTextField fieldUserName;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableAccout;
	private javax.swing.JButton updateBtn;
	// End of variables declaration//GEN-END:variables
}
