/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.HDLD;
import Model.Luong;
import Model.NhanVien;
import Model.PhongBan;
import view.*;

//import javafx.geometry.HPos;
import service.ChucVuService;
import service.HDLDService;
import service.LuongService;
import service.NhanVienService;
import service.PhongBanService;

import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class HSNSView extends javax.swing.JFrame {
	HDLDService hService = new HDLDService();
	NhanVienService nhanVienService = new NhanVienService();
	PhongBanService phongBanService = new PhongBanService();
	LuongService luongService=new LuongService();
	ChucVuService chucVuService =new ChucVuService();
	DefaultTableModel defaultTableModel;

	/**
	 * Creates new form viewHoSoNhanVien
	 */
	public HSNSView() {
		initComponents();
		loadData();
	}

	private void loadData() {
		NhanVienService nhanVienService = new NhanVienService();
		List<NhanVien> nhanvien_data = nhanVienService.findAll();
		defaultTableModel = new DefaultTableModel();
		defaultTableModel.addColumn("Mã Nhân Viên");
		defaultTableModel.addColumn("Họ và tên");
		defaultTableModel.addColumn("Ngày sinh");
		defaultTableModel.addColumn("Giới tính");
		defaultTableModel.addColumn("Số điện thoại");
		defaultTableModel.addColumn("Trình độ");
		defaultTableModel.addColumn("Chuyên môn");
		defaultTableModel.addColumn("CMND");
		defaultTableModel.addColumn("Phòng Ban");
		defaultTableModel.addColumn("Chức vụ");
		defaultTableModel.addColumn("HĐLĐ");
	

		for (NhanVien nv : nhanvien_data) {
			Vector<Object> row = new Vector<Object>();
			for (Object o : nv.toArrayParameter()) {
				row.add(o);
			}
			defaultTableModel.addRow(row);
		}
		tableNhanVien.setModel(defaultTableModel);

		tableNhanVien.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				int index = tableNhanVien.getSelectedRow();
				displayDetails(index);
			
			}
		});
		tableNhanVien.addKeyListener(new KeyAdapter() {
			@Override
			public void keyReleased(KeyEvent e) {
				if ((e.getKeyCode() == KeyEvent.VK_UP) || (e.getKeyCode() == KeyEvent.VK_DOWN)) {
					int index = tableNhanVien.getSelectedRow();
					displayDetails(index);
				}
			}

		});

		DefaultComboBoxModel<String> defaultComboBoxModel = new DefaultComboBoxModel<String>();
		for (PhongBan p : phongBanService.findAll()) {
			defaultComboBoxModel.addElement(p.getTenPhongBan());
		}
		comboBoxRPhongBan.setModel(defaultComboBoxModel);
		comboBoxRPhongBan.setSelectedIndex(-1);
		tableNhanVien.setDefaultEditor(Object.class, null);
	}

	private void displayDetails(int index) {
		String maNhanVien = (String) defaultTableModel.getValueAt(index, 0);
		NhanVien nv = nhanVienService.findById(maNhanVien);
		nv.setChucVu(chucVuService.findById(nv.getMaChucVu()));
		PhongBan pb = phongBanService.findById(nv.getMaPhongBan());
		HDLD hdld = hService.findById(nv.getMaHDLD());
		if (hdld!=null) {
			fieldIDNhanVien.setText(maNhanVien);
			fieldChucVu.setText(nv.getChucVu().getTenChucVu());
			fieldChuyenMon.setText(nv.getChuyenMon());
			fieldCMND.setText(nv.getCMND());
			fieldNgaySinh.setText(nv.getNgaySinh());
			fieldTenNhanVien.setText(nv.getTenNhanVien());
			fieldTrinhDo.setText(nv.getHocVan());
			fieldSDT.setText(nv.getSoDienThoai());
			if (nv.getGioiTinh().equalsIgnoreCase("Nam"))
				namRadio.setSelected(true);
			else
				nuRadio.setSelected(true);
			fieldHDLD.setText(hdld.getIdHDLD());
			fieldHDType.setText(hdld.getTypeHD());
			fieldLuong.setText(""+hdld.getLuongCB());
			fieldHSLuong.setText(""+hdld.getHeSoLuong());
			fieldNgayBD.setText(hdld.getNgayBD());
			fieldNgayKT.setText(hdld.getNgayKT());
			comboBoxRPhongBan.setSelectedItem(pb.getTenPhongBan());	
		}
		

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		sexGeoupBtn = new javax.swing.ButtonGroup();
		panelThongTIn = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		panelTableNhanVien = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableNhanVien = new javax.swing.JTable();
		jPanel6 = new javax.swing.JPanel();
		themBtn = new javax.swing.JButton();
		deleteBtn = new javax.swing.JButton();
		updateBtn = new javax.swing.JButton();
		backMainBtn = new javax.swing.JButton();
		resetField = new javax.swing.JButton();
		hoSoNhanVien = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		fieldIDNhanVien = new javax.swing.JTextField();
		fieldTenNhanVien = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		fieldNgaySinh = new javax.swing.JTextField();
		fieldSDT = new javax.swing.JTextField();
		fieldCMND = new javax.swing.JTextField();
		namRadio = new javax.swing.JRadioButton();
		nuRadio = new javax.swing.JRadioButton();
		labelChucVu = new javax.swing.JLabel();
		fieldChucVu = new javax.swing.JTextField();
		labelPhongBan = new javax.swing.JLabel();
		comboBoxRPhongBan = new javax.swing.JComboBox<String>();
		fieldChuyenMon = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		fieldTrinhDo = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		fieldHDLD = new javax.swing.JTextField();
		fieldHSLuong = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		fieldNgayBD = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		fieldNgayKT = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		fieldLuong = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		fieldHDType = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setPreferredSize(new java.awt.Dimension(1100, 750));
		setResizable(false);

		javax.swing.GroupLayout panelThongTInLayout = new javax.swing.GroupLayout(panelThongTIn);
		panelThongTIn.setLayout(panelThongTInLayout);
		panelThongTInLayout.setHorizontalGroup(panelThongTInLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));
		panelThongTInLayout.setVerticalGroup(panelThongTInLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

		JScrollPane jScrollPane3 = new JScrollPane(comboBoxRPhongBan);

		tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null },
						{ null, null, null, null, null, null, null, null, null, null, null } },
				new String[] { "ID Nhân Viên", "Tên Nhân Viên", "Chức vụ", "Phòng ban", "Trình độ", "Chuyên môn",
						"Ngày sinh", "Giới tính", "SĐT", "CMND", "Mã HĐLĐ" }) {
			Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tableNhanVien);

		javax.swing.GroupLayout panelTableNhanVienLayout = new javax.swing.GroupLayout(panelTableNhanVien);
		panelTableNhanVien.setLayout(panelTableNhanVienLayout);
		panelTableNhanVienLayout.setHorizontalGroup(
				panelTableNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelTableNhanVienLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		panelTableNhanVienLayout.setVerticalGroup(
				panelTableNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(panelTableNhanVienLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jScrollPane2.setViewportView(panelTableNhanVien);
		comboBoxRPhongBan.setSelectedIndex(-1);
		jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		themBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		themBtn.setText("Thêm Nhân Viên");
		themBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				themBtnActionPerformed(evt);
			}
		});

		deleteBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		deleteBtn.setText("Xóa Nhân Viên");
		deleteBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteBtnActionPerformed(evt);
			}
		});

		updateBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		updateBtn.setText("Chỉnh sửa thông tin");
		updateBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateBtnActionPerformed(evt);
			}
		});

		backMainBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		backMainBtn.setText("Trở về");
		backMainBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backMainBtnActionPerformed(evt);
			}
		});

		resetField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		resetField.setText("Reset Field");
		resetField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetFieldActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap().addComponent(themBtn)
						.addGap(95, 95, 95).addComponent(deleteBtn)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(updateBtn).addGap(80, 80, 80).addComponent(resetField).addGap(68, 68, 68)
						.addComponent(backMainBtn)));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(backMainBtn).addComponent(resetField).addComponent(updateBtn))
								.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(themBtn).addComponent(deleteBtn)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		hoSoNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		hoSoNhanVien.setText("HỒ SƠ NHÂN SỰ");

		jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel1.setText("ID Nhân Viên:");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel2.setText("Tên Nhân Viên:");

		fieldIDNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		fieldIDNhanVien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fieldIDNhanVienActionPerformed(evt);
			}
		});

		fieldTenNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		fieldTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				fieldTenNhanVienActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel1)
						.addGap(18, 18, 18)
						.addComponent(fieldIDNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel2).addGap(18, 18, 18).addComponent(fieldTenNhanVien,
								javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(7, 7, 7)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jLabel2)
								.addComponent(fieldIDNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fieldTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel5.setText("Ngày Sinh:");

		jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel6.setText("SĐT:");

		jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel7.setText("CMND:");

		jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel9.setText("Giới tính:");

		fieldNgaySinh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		fieldSDT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		fieldCMND.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		sexGeoupBtn.add(namRadio);
		namRadio.setText("Nam");

		sexGeoupBtn.add(nuRadio);
		nuRadio.setText("Nữ");

		labelChucVu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		labelChucVu.setText("Chức vụ:");

		fieldChucVu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		labelPhongBan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		labelPhongBan.setText("Phòng ban:");

		comboBoxRPhongBan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		fieldChuyenMon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel4.setText("Chuyên môn:");

		fieldTrinhDo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel3.setText("Trình độ:");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addComponent(jLabel3).addGap(56, 56, 56)
								.addComponent(fieldTrinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5).addComponent(jLabel6))
								.addGap(45, 45, 45)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(fieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(fieldNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel4Layout.createSequentialGroup().addComponent(labelChucVu).addGap(59, 59, 59)
								.addComponent(fieldChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(18, 18, 18)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel4Layout.createSequentialGroup()
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel7).addComponent(jLabel9))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(jPanel4Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addGroup(jPanel4Layout.createSequentialGroup().addComponent(namRadio)
														.addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(nuRadio))
												.addComponent(fieldCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(4, 4, 4)
										.addComponent(labelPhongBan).addGap(45, 45, 45)
										.addComponent(comboBoxRPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(2, 2, 2).addComponent(jLabel4)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(fieldChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(25, 25, 25)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addGroup(jPanel4Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9).addComponent(namRadio).addComponent(nuRadio))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel7).addComponent(fieldCMND,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(labelPhongBan).addComponent(comboBoxRPhongBan,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel4).addComponent(fieldChuyenMon,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel5).addComponent(fieldNgaySinh,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel6).addComponent(fieldSDT,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(labelChucVu).addComponent(fieldChucVu,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel3).addComponent(fieldTrinhDo,
												javax.swing.GroupLayout.PREFERRED_SIZE, 30,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
		jLabel11.setText("Thông tin:");

		jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel12.setText("Mã HĐLĐ:");

		jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel14.setText("Hệ số lương:");

		fieldHDLD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		fieldHSLuong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel16.setText("Ngày BĐ:");

		fieldNgayBD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel17.setText("Ngày KT:");

		fieldNgayKT.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel18.setText("Lương CB:");

		fieldLuong.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
		jLabel13.setText("Loại HĐ:");

		fieldHDType.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel12).addComponent(jLabel16).addComponent(jLabel18)
								.addComponent(jLabel17).addComponent(jLabel14).addComponent(jLabel13))
						.addGap(27, 27, 27)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(fieldHSLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fieldHDType, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fieldNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fieldLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fieldHDLD, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(fieldNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel12).addComponent(fieldHDLD, javax.swing.GroupLayout.PREFERRED_SIZE,
										30, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel18).addComponent(fieldLuong, javax.swing.GroupLayout.PREFERRED_SIZE,
										30, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(fieldHDType, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel13))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(fieldHSLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel14))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel16).addComponent(fieldNgayBD,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel17).addComponent(fieldNgayKT,
										javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(39, 39, 39)));

		jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
		jLabel15.setText("Hợp đồng:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jScrollPane2).addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel11)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(hoSoNhanVien, javax.swing.GroupLayout.Alignment.TRAILING))
								.addGap(42, 42, 42)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel15))))
				.addGap(0, 33, Short.MAX_VALUE)
				.addComponent(panelThongTIn, javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(93, 93, 93)
						.addComponent(panelThongTIn, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(32, 32, 32).addComponent(hoSoNhanVien)
								.addGap(18, 18, 18)
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(19, 19, 19).addComponent(jLabel11).addGap(18, 18, 18)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7,
										Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel15).addGap(18, 18, 18)
								.addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)))
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(47, 47, 47)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void fieldIDNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldIDNhanVienActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_fieldIDNhanVienActionPerformed

	private void fieldTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fieldTenNhanVienActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_fieldTenNhanVienActionPerformed

	private void backMainBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backMainBtnActionPerformed
		NHANSUView nhanSuView = new NHANSUView();
		nhanSuView.setVisible(true);
		nhanSuView.setLocationRelativeTo(null);
		nhanSuView.setResizable(false);
		this.dispose();
	}// GEN-LAST:event_backMainBtnActionPerformed

	private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_themBtnActionPerformed
		ThemNhanVienView themNhanVienView=new ThemNhanVienView();
		themNhanVienView.setVisible(true);
		themNhanVienView.setLocationRelativeTo(null);
		themNhanVienView.setResizable(false);
		themNhanVienView.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		this.dispose();
	}
	// GEN-LAST:event_themBtnActionPerformed

	private void resetFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetFieldActionPerformed
		resetField();

	}// GEN-LAST:event_resetFieldActionPerformed

	private void resetField() {
		fieldIDNhanVien.setText("");
		fieldTenNhanVien.setText("");
		fieldChucVu.setText("");
		fieldTrinhDo.setText("");
		fieldChuyenMon.setText("");
		fieldNgaySinh.setText("");
		fieldSDT.setText("");
		fieldCMND.setText("");
		fieldHDLD.setText("");
		fieldLuong.setText("");
		fieldHSLuong.setText("");
		fieldNgayBD.setText("");
		fieldNgayKT.setText("");
		fieldHDType.setText("");
		comboBoxRPhongBan.setSelectedIndex(-1);
	}

	private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBtnActionPerformed
		int selectedIndex = tableNhanVien.getSelectedRow();
		String maNhanVien = (String) defaultTableModel.getValueAt(selectedIndex, 0);
		NhanVien nhanVien =nhanVienService.findById(maNhanVien);
		Luong l =luongService.findByMaNhanVien(maNhanVien);
		luongService.delete(l);
		if (JOptionPane.showConfirmDialog(this, "Bạn thật sự muốn xóa dữ liệu này ?","Thông báo xóa",JOptionPane.OK_CANCEL_OPTION)==JOptionPane.OK_OPTION) {
			if(nhanVienService.delete(nhanVien)) {
				JOptionPane.showMessageDialog(this, "Xoa Nhan Vien Thanh Cong");
				loadData();
				resetField();
			} else {
				JOptionPane.showMessageDialog(this, "Xóa  Nhan Vien Khong Thanh Cong");
			}
		}
		
		
		
	}// GEN-LAST:event_deleteBtnActionPerformed

	private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateBtnActionPerformed
		int selectedIndex = tableNhanVien.getSelectedRow();
		if (selectedIndex!=-1) {
			String maNhanVien = (String) defaultTableModel.getValueAt(selectedIndex, 0);
			  SuaNhanVienView suaNhanVienView = new SuaNhanVienView(maNhanVien);
			  suaNhanVienView.setVisible(true);
			  suaNhanVienView.setLocationRelativeTo(null);
			  suaNhanVienView.setResizable(false);
			  suaNhanVienView.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
	          this.dispose();
		}else {
			JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên muốn cập nhật");
		}

//          this.dispose();

	}// GEN-LAST:event_updateBtnActionPerformed

	/**
	 * @param args the command line ar
	 * guments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HSNSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HSNSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HSNSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HSNSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				HSNSView viewHSNV = new HSNSView();
				viewHSNV.setVisible(true);
				viewHSNV.setLocationRelativeTo(null);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton backMainBtn;
	private javax.swing.JButton deleteBtn;
	private javax.swing.JTextField fieldCMND;
	private javax.swing.JTextField fieldChucVu;
	private javax.swing.JTextField fieldChuyenMon;
	private javax.swing.JTextField fieldHDLD;
	private javax.swing.JTextField fieldHDType;
	private javax.swing.JTextField fieldHSLuong;
	private javax.swing.JTextField fieldIDNhanVien;
	private javax.swing.JTextField fieldLuong;
	private javax.swing.JTextField fieldNgayBD;
	private javax.swing.JTextField fieldNgayKT;
	private javax.swing.JTextField fieldNgaySinh;
	private JComboBox<String> comboBoxRPhongBan;
	private javax.swing.JTextField fieldSDT;
	private javax.swing.JTextField fieldTenNhanVien;
	private javax.swing.JTextField fieldTrinhDo;
	private javax.swing.JLabel hoSoNhanVien;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel labelChucVu;
	private javax.swing.JLabel labelPhongBan;
	private javax.swing.JRadioButton namRadio;
	private javax.swing.JRadioButton nuRadio;
	private javax.swing.JPanel panelTableNhanVien;
	private javax.swing.JPanel panelThongTIn;
	private javax.swing.JButton resetField;
	private javax.swing.ButtonGroup sexGeoupBtn;
	private javax.swing.JTable tableNhanVien;
	private javax.swing.JButton themBtn;
	private javax.swing.JButton updateBtn;
	// End of variables declaration//GEN-END:variables
}
