/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import view.*;

/**
 *
 * @author asus
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinhView
     */
	public MainView() {
        setTitle("Hệ thống Nhân sự & Tiền lương");
        initComponents();   
        
    }
    public MainView(String key) {
        setTitle("Hệ thống Nhân sự & Tiền lương");
        initComponents();   
        switch (key) {
		case "nhansu":
			keToanBtn.setEnabled(false);
			heThongBtn.setEnabled(false);
			break;
		case "ketoan":
			nhanSuBtn.setEnabled(false);
			heThongBtn.setEnabled(false);
			break;
		case "admin":
                        keToanBtn.setEnabled(false);
			nhanSuBtn.setEnabled(false);
			
			break;
		}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nhanSuBtn = new javax.swing.JButton();
        keToanBtn = new javax.swing.JButton();
        heThongBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dangXuatBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 750));
        setResizable(false);

        nhanSuBtn.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        nhanSuBtn.setText("QUẢN LÝ NHÂN SỰ");
        nhanSuBtn.setPreferredSize(new java.awt.Dimension(200, 55));
        nhanSuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanSuBtnActionPerformed(evt);
            }
        });

        keToanBtn.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        keToanBtn.setText("KẾ TOÁN");
        keToanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keToanBtnActionPerformed(evt);
            }
        });

        heThongBtn.setFont(new java.awt.Font("Times New Roman", 0, 40)); // NOI18N
        heThongBtn.setText("QUẢN TRỊ HỆ THỐNG");
        heThongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heThongBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỆ THỐNG QUẢN LÝ NHÂN SỰ TIỀN LƯƠNG");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("UVN Thang Gieng", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CÔNG TY CỔ PHẦN VỐN TDS");

        dangXuatBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dangXuatBtn.setForeground(new java.awt.Color(255, 0, 0));
        dangXuatBtn.setText("ĐĂNG XUẤT");
        dangXuatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nhanSuBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keToanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heThongBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dangXuatBtn)
                .addGap(394, 394, 394))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(nhanSuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(keToanBtn)
                .addGap(61, 61, 61)
                .addComponent(heThongBtn)
                .addGap(73, 73, 73)
                .addComponent(dangXuatBtn)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nhanSuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanSuBtnActionPerformed
                NHANSUView nhansuView = new NHANSUView();
                nhansuView.setVisible(true);
                nhansuView.setLocationRelativeTo(null);
                nhansuView.setResizable(false);
                this.dispose();
    }//GEN-LAST:event_nhanSuBtnActionPerformed

    private void keToanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keToanBtnActionPerformed
                KETOANView ketoanView = new KETOANView();
                ketoanView.setVisible(true);
                ketoanView.setLocationRelativeTo(null);
                ketoanView.setResizable(false);
                this.dispose();
    	
    }//GEN-LAST:event_keToanBtnActionPerformed

    private void heThongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heThongBtnActionPerformed
                HETHONGView hethongView = new HETHONGView();
                hethongView.setVisible(true);
                hethongView.setLocationRelativeTo(null);
                hethongView.setResizable(false);
                this.dispose();
    }//GEN-LAST:event_heThongBtnActionPerformed

    private void dangXuatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatBtnActionPerformed
            CHECKVALIDView checkValid = new CHECKVALIDView();
            checkValid.setVisible(true);
            checkValid.setLocationRelativeTo(null);
            checkValid.setResizable(false);
            Main.tk = null;
            this.dispose();
    }//GEN-LAST:event_dangXuatBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangXuatBtn;
    private javax.swing.JButton heThongBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton keToanBtn;
    private javax.swing.JButton nhanSuBtn;
    // End of variables declaration//GEN-END:variables
}
