/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import Model.HDLD;
import Model.Luong;
import Model.NhanVien;
import view.*;
import service.LuongService;
import service.NhanVienService;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class TienLuongView extends javax.swing.JFrame {
	LuongService luongService =new LuongService();
	NhanVienService nhanVienService =new NhanVienService();
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form TienLuongView
     */
    public TienLuongView() {
            
        setTitle("Tien Luong Nhan Vien");
        initComponents();
        loadData();
       
    }

    public void loadData() {
    	defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Id Nhân viên");
        defaultTableModel.addColumn("Tên Nhân Viên");
        defaultTableModel.addColumn("Lương CB");
        defaultTableModel.addColumn("Hệ Số Lương");
        defaultTableModel.addColumn("Tiền Thưởng");
        defaultTableModel.addColumn("Lương Ứng");
        defaultTableModel.addColumn("Tiền Phạt");
        defaultTableModel.addColumn("Lương Tổng");
        List<Luong> data =luongService.findAll();
        for (Luong luong : data) {
			String maNhanVien = luong.getIdNhanVien();
			NhanVien nv  = nhanVienService.findById(maNhanVien);
			Vector<Object> v = new Vector<Object>();
			v.add(maNhanVien);
			v.add(nv.getTenNhanVien());
			v.add(luong.getLuongCb());
			v.add(luong.getHsLuong());
			v.add(luong.getTienThuong());
			v.add(luong.getLuongUng());
			v.add(luong.getTienPhat());
			v.add(luong.getTongLuong());
			defaultTableModel.addRow(v);
		}
        tableLuongNV.setModel(defaultTableModel);
        fieldIDNV.setEnabled(false);
        tableLuongNV.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyReleased(KeyEvent e) {
        		if(e.getKeyCode()==KeyEvent.VK_UP||e.getKeyCode()==KeyEvent.VK_DOWN) {
        			int index = tableLuongNV.getSelectedRow();
        			displayDetails(index);
        		}
        	}
		});
        tableLuongNV.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		int index = tableLuongNV.getSelectedRow();
        		displayDetails(index);
        	}
		});
        
    }
    private void displayDetails(int index) {
    	String maNhanVien = (String) defaultTableModel.getValueAt(index, 0);
    	Luong luong=luongService.findByMaNhanVien(maNhanVien);
    	fieldIDNV.setText(luong.getIdNhanVien());
    	fieldLuongUng.setText(""+luong.getLuongUng());
    	fieldTienPhat.setText(""+luong.getTienPhat());
    	fieldTienThuong.setText(""+luong.getTienThuong());
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLuongNV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tongLuongBtn = new javax.swing.JButton();
        fieldTienThuong = new javax.swing.JTextField();
        fieldTienPhat = new javax.swing.JTextField();
        fieldLuongUng = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldIDNV = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tableLuongNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Nhân viên", "Tên Nhân Viên", "Lương CB", "Hệ số lương", "Tiền thưởng", "Tiền trừ", "Lương Ứng", "Tổng Lương"
            }
        ));
        jScrollPane1.setViewportView(tableLuongNV);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("BẢNG LƯƠNG NHÂN VIÊN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Tiền Thưởng:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Tiền Phạt:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Lương Ứng:");

        tongLuongBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tongLuongBtn.setText("Tổng Lương");
        tongLuongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tongLuongBtnActionPerformed(evt);
            }
        });

        fieldTienThuong.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        fieldTienPhat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        fieldLuongUng.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("ID Nhân Viên:");

        fieldIDNV.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        backBtn.setText("Trở về");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(298, 298, 298)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(fieldTienThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(107, 107, 107))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(tongLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(fieldTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldLuongUng, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 169, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(fieldIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIDNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTienThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTienPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldLuongUng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tongLuongBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tongLuongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tongLuongBtnActionPerformed
    	int index= tableLuongNV.getSelectedRow();
    	if (index!=-1) {
    		String maNhanVien = (String) defaultTableModel.getValueAt(index, 0);
        	Luong luong = luongService.findByMaNhanVien(maNhanVien);
        	int luongUng = Integer.parseInt(fieldLuongUng.getText());
        	int tienPhat = Integer.parseInt(fieldTienPhat.getText());
        	int tienThuong = Integer.parseInt(fieldTienThuong.getText());
        	long tongLuong = (long) (luong.getHsLuong()*luong.getLuongCb()-luongUng-tienPhat+tienThuong);
        	luong.setLuongUng(luongUng);
        	luong.setTienPhat(tienPhat);
        	luong.setTienThuong(tienThuong);
        	luong.setTongLuong(tongLuong);
        	if (luongService.update(luong)) {
				JOptionPane.showMessageDialog(this, "chốt lương thành công");
				loadData();
			}else {
				System.out.println(luong);
				JOptionPane.showMessageDialog(this, "chốt lương không thành công");

			}
        	
		}
    	
    	
    }//GEN-LAST:event_tongLuongBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       NHANSUView nhanSuView = new NHANSUView();
       nhanSuView.setVisible(true);
       nhanSuView.setLocationRelativeTo(null);
       nhanSuView.setResizable(false);
       this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TienLuongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TienLuongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TienLuongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TienLuongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TienLuongView tienLuongView = new TienLuongView();
                tienLuongView.setVisible(true);
                tienLuongView.setLocationRelativeTo(null);
                tienLuongView.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField fieldIDNV;
    private javax.swing.JTextField fieldLuongUng;
    private javax.swing.JTextField fieldTienPhat;
    private javax.swing.JTextField fieldTienThuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLuongNV;
    private javax.swing.JButton tongLuongBtn;
    // End of variables declaration//GEN-END:variables
}
